import "./globals.css"
import { Inter } from "next/font/google"
import { Providers } from "@/components/Providers"
import { SignInButton } from "@/components/SignInButton"
import { NavBar } from "@/components/NavBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Real Estate CRM",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100 text-slate-800`}>
        <Providers>
          {/* <NavBar /> */}
          {/* <SignInButton /> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
